backend:
  name: git-gateway
  repo: tepelaptop-boop/glittery-torte-772bd3
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "news"
    label: "Εφημερίδα"
    files:
      - label: "Άρθρα Εφημερίδας"
        name: "articles"
        file: "articles.json"
        fields:
          - label: "Λίστα Άρθρων"
            name: "articles"
            widget: "list"
            fields:
              - { label: "Τίτλος", name: "title", widget: "string" }
              - { label: "Ημερομηνία", name: "date", widget: "string" }
              - { label: "Περιεχόμενο", name: "content", widget: "text" }
